version: '3.1'

services:

  db:
    image: postgres
    restart: always
    container_name: postgres-db
    volumes:
      - './postgres_data:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: real-estate-publication-system-db
    ports:
      - '5432:5432'